version: '3.8'

services:
  # Prometheus Metrics Collection
  prometheus:
    image: prom/prometheus:latest
    container_name: malsift_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - malsift_network

  # Grafana Dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: malsift_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - malsift_network

volumes:
  prometheus_data:
  grafana_data:

networks:
  malsift_network:
    external: true
